version: '3.4'

services:
  rc09useeffectaxios:
    image: rc09useeffectaxios
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
